apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-trading-system.fullname" . }}
  labels:
    {{- include "demo-trading-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-trading-system.selectorLabels" . | nindent 4 }}
